import { ChangeDetectionStrategy, Component, computed, effect, inject, input } from '@angular/core';
import { Title } from '@angular/platform-browser';
import { DatePipe } from '@angular/common';
import { RouterLink } from '@angular/router';

import { ContentStore } from '../../core/content-store';
import { categoryMeta, Category } from '../../core/models/article';
import { brandInitials, brandStyle } from '../../core/brand';
import { ArticleCard } from '../../shared/article-card/article-card';

@Component({
  selector: 'app-article-detail',
  imports: [ArticleCard, RouterLink, DatePipe],
  templateUrl: './article-detail.html',
  styleUrl: './article-detail.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[style]': 'accent()' },
})
export class ArticleDetail {
  /** From the route's `data.category`. */
  readonly category = input.required<Category>();
  /** From the `:slug` path parameter. */
  readonly slug = input.required<string>();

  private readonly store = inject(ContentStore);
  private readonly title = inject(Title);

  protected readonly meta = computed(() => categoryMeta(this.category()));
  protected readonly loading = computed(() => this.store.isLoading(this.category())());
  protected readonly article = computed(() =>
    this.store
      .articles(this.category())()
      .find((a) => a.slug === this.slug()),
  );
  protected readonly related = this.store.related(this.article, 3);

  protected readonly accent = computed(() => brandStyle(this.article()?.brand ?? ''));
  protected readonly initials = computed(() => brandInitials(this.article()?.brand ?? ''));

  /**
   * Archived posts have summaries generated by truncating their opening
   * paragraph, so showing both would print the same sentence twice.
   */
  protected readonly showSummary = computed(() => {
    const post = this.article();
    if (!post) {
      return false;
    }
    const opening = post.body[0];
    if (!opening) {
      return true;
    }
    const head = post.summary.replace(/…$/, '').trim();
    return !opening.startsWith(head.slice(0, 60));
  });

  constructor() {
    effect(() => {
      const post = this.article();
      this.title.setTitle(post ? `${post.productName} — We Love Silicon` : 'We Love Silicon');
    });
  }
}
